Sprint 4 Plan
omarkhater-school/NXTFolio pull request #15
Opened 2024-11-09 05:48 UTC by LikhithReddyM

2024-11-09 05:48 UTC, ManikantaGudipudi approved these changes

2024-11-09 05:58 UTC, Caroline-tamu approved these changes

2024-11-09 21:33 UTC, omarkhater-school requested changes
Please separate the sprint 4 plan from edit gallery feature pull request

2024-11-11 06:18 UTC, BranHill21 approved these changes

2024-11-11 06:41 UTC, Caroline-tamu approved these changes

2024-11-11 17:09 UTC, HonraoYash approved these changes

2024-11-12 00:49 UTC, omarkhater-school approved these changes

2024-11-12 00:50 UTC, omarkhater-school commented
Just please rename the pull request to be "Edit Feature" or similar instead of current "Sprint 4 plan"

2024-11-12 23:00 UTC, merged